name: WhiteSource Scan

on:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: WhiteSource Scan Runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Run WhiteSource Scan Action
        uses: trimble-oss/gh-actions/mend-scanner@main

        with:
          apiKey: ${{ secrets.WSS_API_KEY }}
          configFile: 'wss-unified-agent.config'
